
# (C) 2014 CarrierWrt.org

#
# Target: ramips
#

define Target/ramips

	CONFIG += \
		CONFIG_TARGET_ramips=y \
		CONFIG_TARGET_ROOTFS_JFFS2=n

	IMAGES := \
		ramips/openwrt-ramips-rt305x-all0256n-8M-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-all5002-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-all5003-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-argus_atp52b-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-asl26555-16M-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-asl26555-8M-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-awm002-evb-8M-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-bc2-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-belkinf7c027-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-broadway-squashfs-factory.bin \
		ramips/openwrt-ramips-rt305x-broadway-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-carambola-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-dap-1350-squashfs-factory.bin \
		ramips/openwrt-ramips-rt305x-dap-1350-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-dap-1350WW-squashfs-factory.bin \
		ramips/openwrt-ramips-rt305x-dap-1350WW-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-dir-320-b1-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-dir-610-a1-squashfs-factory.bin \
		ramips/openwrt-ramips-rt305x-dir-610-a1-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-dir-620-a1-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-dir-620-d1-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-f5d8235v2-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-fonera20n-squashfs-factory.bin \
		ramips/openwrt-ramips-rt305x-fonera20n-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-freestation5-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-hw550-3g-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-ip2202-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-m4-8M-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-m4-squashfs-8M-factory.bin \
		ramips/openwrt-ramips-rt305x-mofi3500-3gn-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-mpr-a2-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-mzk-w300nh2-squashfs-factory.bin \
		ramips/openwrt-ramips-rt305x-mzk-w300nh2-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-ncs601W-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-omni-emb-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-omni-plug-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-pwh2004-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-rt-n13u-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-rut5xx-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-vocore-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-w502u-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-wr512-3ng-8M-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-wr6202-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-x5-squashfs-factory.bin \
		ramips/openwrt-ramips-rt305x-x5-squashfs-sysupgrade.bin \
		ramips/openwrt-ramips-rt305x-x8-squashfs-factory.bin \
		ramips/openwrt-ramips-rt305x-x8-squashfs-sysupgrade.bin

endef
