#!/bin/sh

if [ "$UCI_MIGRATION_ACTION" == "RESET" ]; then
	# Set LAN ip address to mimize risk of collision
	uci set network.lan.ipaddr=192.168.8.1
	uci commit network

	# Set product as hostname
	uci set system.@system[0].hostname=carrier-rgw
	uci commit system
	echo $(uci get system.@system[0].hostname) > /proc/sys/kernel/hostname
fi

exit 0
