#!/bin/sh

if [ "$UCI_MIGRATION_ACTION" == "RESET" ]; then
	# Set product as hostname
	uci set system.@system[0].hostname=carrier-appliance
	uci commit system
	echo $(uci get system.@system[0].hostname) > /proc/sys/kernel/hostname
fi

exit 0
