
# (C) 2013 CarrierWrt.org

#
# Target: x86full
#

define Target/x86full

  CONFIG += \
    CONFIG_TARGET_x86=y \
    CONFIG_TARGET_ROOTFS_CPIOGZ=y \
    CONFIG_TARGET_ROOTFS_JFFS2=n

  IMAGES :=
		x86/openwrt-x86-generic-combined-squashfs.img \
		x86/openwrt-x86-generic-combined-ext4.img.gz
   
endef
