
# (C) 2013 CarrierWrt.org

#
# Target: x86full
#

define Target/x86full

	CONFIG += \
		CONFIG_TARGET_x86=y \
		CONFIG_TARGET_x86_generic=y \
		CONFIG_TARGET_x86_generic_Generic=y \
		CONFIG_X86_VDI_IMAGES=y \
		CONFIG_X86_VMDK_IMAGES=y \
		CONFIG_TARGET_ROOTFS_CPIOGZ=y \
		CONFIG_TARGET_ROOTFS_JFFS2=n

	IMAGES := \
		x86/openwrt-x86-generic-combined-ext4.img.gz \
		x86/openwrt-x86-generic-combined-ext4.vdi \
		x86/openwrt-x86-generic-combined-ext4.vmdk \
		x86/openwrt-x86-generic-combined-squashfs.img \
		x86/openwrt-x86-generic-rootfs.cpio.gz \
		x86/openwrt-x86-generic-rootfs-ext4.img.gz \
		x86/openwrt-x86-generic-rootfs-squashfs.img \
		x86/openwrt-x86-generic-rootfs.tar.gz \
		x86/openwrt-x86-generic-vmlinuz \

endef
