#!/bin/sh

PERSIST=/etc/factory-defaults/persist

MAC=$(uci get wireless.radio0.macaddr | tr 'a-f' 'A-F')

# Initialize persistent variables
[ -e $PERSIST/SSID ] || \
	echo "carrierwrt-$(echo $MAC | cut -c10-17 | tr -d ':')" > $PERSIST/SSID

if [ "$UCI_MIGRATION_ACTION" == "RESET" ]; then
	# Set up wireless as open network per default
	uci delete wireless.radio0.disabled
	uci set wireless.@wifi-iface[0].ssid="$(cat $PERSIST/SSID)"
	# If there happens to be a factory default KEY we use it
	if [ -f $PERSIST/KEY ]; then
		uci set wireless.@wifi-iface[0].encryption=psk-mixed
		uci set wireless.@wifi-iface[0].key="$(cat $PERSIST/KEY)"
	fi
	uci commit wireless

	# Set bootstrap as theme in luci
	uci set luci.main.mediaurlbase=/luci-static/bootstrap
	uci commit luci
fi

exit 0
