
# (C) 2013 CarrierWrt.org

#
# Target: malta
#

define Target/malta

	CONFIG += \
		CONFIG_TARGET_malta=y \
		CONFIG_TARGET_ROOTFS_JFFS2=n

	IMAGES := \
		openwrt-malta-be-vmlinux-initramfs.elf  \
		openwrt-malta-be64-vmlinux-initramfs.elf  \
		openwrt-malta-le-vmlinux-initramfs.elf  \
		openwrt-malta-le64-vmlinux-initramfs.elf  


endef
