# (C) 2013 CarrierWrt.org

#
# Example product customization:
#
#	 Access point for an office network
#

define Customization/anyfinetworks

	CONFIG += 

	SETTINGS := uci-customization.sh

	TESTED := \
		ar71xx/openwrt-ar71xx-generic-tl-wr941nd-v2-squashfs-factory.bin \
		ar71xx/openwrt-ar71xx-generic-tl-wr941nd-v2-squashfs-sysupgrade.bin \
		ar71xx/openwrt-ar71xx-generic-ubnt-nano-m-squashfs-factory.bin \
		ar71xx/openwrt-ar71xx-generic-ubnt-nano-m-squashfs-sysupgrade.bin \
		ar71xx/openwrt-ar71xx-generic-ubnt-rocket-m-squashfs-factory.bin \
		ar71xx/openwrt-ar71xx-generic-ubnt-rocket-m-squashfs-sysupgrade.bin

endef
