
# (C) 2013 CarrierWrt.org

#
# Product profile: rgw (Residential Gateway)
#

define Product/rgw

  CONFIG += \
  		CONFIG_PACKAGE_luci=y
		  
  SETTINGS = uci-rgw.sh

endef

define Customization/default

  CONFIG += \
		CONFIG_PACKAGE_luci-theme-bootstrap=y
	
  SETTINGS = uci-defaults.sh

endef
